CI: simple test

diff --git a/.github/workflows/docker.yml b/.github/workflows/docker.yml
--- a/.github/workflows/docker.yml
+++ b/.github/workflows/docker.yml
@@ -10,19 +10,19 @@ jobs:
     strategy:
       matrix:
         include:
-          - { image: v6, node: 6.10 }
-          - { image: v7 }
-          - { image: v8 }
-          - { image: v9 }
-          - { image: v10 }
-          - { image: v11 }
-          - { image: v12 }
-          - { image: v13 }
-          - { image: v14 }
-          - { image: v15 }
-          - { image: v16 }
-          - { image: v17 }
-          - { image: v18 }
+          - image: v6
+          - image: v7
+          - image: v8
+          - image: v9
+          - image: v10
+          - image: v11
+          - image: v12
+          - image: v13
+          - image: v14
+          - image: v15
+          - image: v16
+          - image: v17
+          - image: v18
 
       fail-fast: false
 
@@ -44,10 +44,35 @@ jobs:
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v2
 
-      - name: Build and push
+      - name: Build docker image
         uses: docker/build-push-action@v3
         with:
           context: ${{ matrix.image }}
           push: false
           tags: dockette/nodejs:${{ matrix.image }}
-          platforms: ${{ matrix.platforms || 'linux/amd64,linux/arm64' }}
+          platforms: linux/amd64,linux/arm64
+
+      - name: Load docker image
+        uses: docker/build-push-action@v3
+        with:
+          context: ${{ matrix.image }}
+          load: true
+          tags: dockette/nodejs:${{ matrix.image }}
+
+      - name: Test node version
+        run: |
+          var="$(docker run --rm dockette/nodejs:${{ matrix.image }} node -v)"
+          if [[ $var =~ "${{ matrix.image }}" ]]; then
+              echo "Node version matched ${var} =~ ${{ matrix.image }}"
+          else
+              echo "Invalid node version ${var} != ${{ matrix.image }}"
+              exit 255
+          fi
+
+      - name: Push docker image
+        uses: docker/build-push-action@v3
+        with:
+          context: ${{ matrix.image }}
+          push: true
+          tags: dockette/nodejs:${{ matrix.image }}
+          platforms: linux/amd64,linux/arm64
